//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NR2K3_Season_Manager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PracticeResult
    {
        public int Id { get; set; }
        public bool IsHappyHour { get; set; }
        public float Time { get; set; }
    
        public virtual WeekendResult WeekendResult { get; set; }
    }
}
