//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NR2K3_Season_Manager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Race
    {
        public Race()
        {
            this.WeekendResults = new HashSet<WeekendResult>();
        }
    
        public int Id { get; set; }
        public bool IsExhibition { get; set; }
        public string RaceName { get; set; }
        public string TrackName { get; set; }
        public short RaceDistance { get; set; }
        public Nullable<int> PlayoffRoundId { get; set; }
    
        public virtual Season Season { get; set; }
        public virtual ICollection<WeekendResult> WeekendResults { get; set; }
        public virtual PlayoffRound PlayoffRound { get; set; }
    }
}
