//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NR2K3_Season_Manager.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SeriesDataModelContainer : DbContext
    {
        public SeriesDataModelContainer()
            : base("name=SeriesDataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Driver> Drivers { get; set; }
        public DbSet<Team> Teams { get; set; }
        public DbSet<Manufacturer> Manufacturers { get; set; }
        public DbSet<Series> Series { get; set; }
        public DbSet<Season> Seasons { get; set; }
        public DbSet<Race> Races { get; set; }
        public DbSet<RaceResult> RaceResults { get; set; }
        public DbSet<QualifyingResult> QualifyingResults { get; set; }
        public DbSet<WeekendResult> WeekendResults { get; set; }
        public DbSet<StageResult> StageResults { get; set; }
        public DbSet<PracticeResult> PracticeResults { get; set; }
        public DbSet<PointsSystem> PointsSystems { get; set; }
        public DbSet<Position> Positions { get; set; }
        public DbSet<PlayoffRound> PlayoffRounds { get; set; }
        public DbSet<Penalty> Penalties { get; set; }
        public DbSet<PointsResult> PointsResults { get; set; }
    }
}
