
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NR2K3_Season_Manager.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Driver
{

    public Driver()
    {

        this.WeekendResults = new HashSet<WeekendResult>();

        this.Seasons = new HashSet<Season>();

    }


    public int Id { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Sponsor { get; set; }

    public byte CarNumber { get; set; }

    public bool isRookie { get; set; }



    public virtual Team Team { get; set; }

    public virtual ICollection<WeekendResult> WeekendResults { get; set; }

    public virtual ICollection<Season> Seasons { get; set; }

}

}
