
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NR2K3_Season_Manager.Model
{

using System;
    using System.Collections.Generic;
    
public partial class PointsSystem
{

    public PointsSystem()
    {

        this.Positions = new HashSet<Position>();

        this.PlayoffRounds = new HashSet<PlayoffRound>();

        this.Seasons = new HashSet<Season>();

    }


    public int Id { get; set; }

    public short LedLad { get; set; }

    public short MostLapsLed { get; set; }



    public virtual ICollection<Position> Positions { get; set; }

    public virtual ICollection<PlayoffRound> PlayoffRounds { get; set; }

    public virtual ICollection<Season> Seasons { get; set; }

}

}
