
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NR2K3_Season_Manager.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Season
{

    public Season()
    {

        this.Races = new HashSet<Race>();

        this.Drivers = new HashSet<Driver>();

    }


    public int Id { get; set; }

    public byte SeasonNumber { get; set; }

    public int PointsSystemId { get; set; }

    public string Roster { get; set; }

    public string NR2K3Root { get; set; }



    public virtual Series Series { get; set; }

    public virtual ICollection<Race> Races { get; set; }

    public virtual ICollection<Driver> Drivers { get; set; }

    public virtual PointsSystem PointsSystem { get; set; }

}

}
