
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NR2K3_Season_Manager.Model
{

using System;
    using System.Collections.Generic;
    
public partial class Series
{

    public Series()
    {

        this.Seasons = new HashSet<Season>();

    }


    public int Id { get; set; }

    public string SeriesName { get; set; }

    public string SeriesLogo { get; set; }

    public string SanctioningLogo { get; set; }

    public string SeriesShort { get; set; }



    public virtual ICollection<Season> Seasons { get; set; }

}

}
