
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace NR2K3_Season_Manager.Model
{

using System;
    using System.Collections.Generic;
    
public partial class WeekendResult
{

    public WeekendResult()
    {

        this.StageResults = new HashSet<StageResult>();

        this.PracticeResults = new HashSet<PracticeResult>();

    }


    public int Id { get; set; }



    public virtual Race Race { get; set; }

    public virtual QualifyingResult QualifyingResult { get; set; }

    public virtual RaceResult RaceResult { get; set; }

    public virtual Driver Driver { get; set; }

    public virtual ICollection<StageResult> StageResults { get; set; }

    public virtual ICollection<PracticeResult> PracticeResults { get; set; }

    public virtual PointsResult PointsResult { get; set; }

}

}
